baseURL = "https://blog.lakatoslab.info"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Diego Verissimo Lakatos' blog"
theme = "hugo-blog-awesome"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = 'github.com/hugo-sid/hugo-blog-awesome'

[params]
title = "Diego Verissimo Lakatos' blog"

description = "Blog about DevOps, Cloud Computing and containers"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

#staticDir = ["images"]
[params.author]
  name = "Diego Verissimo Lakatos"
  email = "uiodwhu@hnuidhw.com"
## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/diegolakatos/"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:diegovlakatos@gmail.com"

[Languages]
  [Languages.en]
  title = "Diego V Lakatos"
  weight = 1
  LanguageName = "English"

  [Languages.pt]
  title = "Diego V Lakatos"
  description = "Blog sobre DevOps, Cloud Computing, Linux e tecnologias correlatas"
  weight = 2
  LanguageName = "Portuguese"

[permalinks]
  posts = "/:year/:month/:title/"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

 [[Languages.pt.menu.main]]
 url    = "/pt/"
 identifier = "home"
 name   = "Pagina Inicial"
 weight = 100

 [[Languages.pt.menu.main]]
 name = "Posts"
 weight = 200
 identifier = "posts"
 url = "/pt/post/"

 [[Languages.pt.menu.main]]
 name = "Sobre"
 weight = 300
 identifier = "about"
 url = "/pt/about/"
